Feature/db schema
MateuszMieczkowski/OnlineStore pull request #5
Opened 2023-11-03 22:09 UTC by MateuszMieczkowski

2023-11-03 22:10 UTC, MateuszMieczkowski commented
Jednak pomyślałem, że 2 tabele na klientów i na adminów nie ma sensu a tylko nie potrzebnie komplikuje. A i tak wystarczająco mamy tabel

2023-11-04 12:21 UTC, michal-jablonski requested changes

2023-11-04 12:21 UTC, michal-jablonski commented on Server/Entities/UserPreference.cs
> +}
do preferencji jeszcze potrzebujemy czy klient chce wyświetlać ceny w netto czy brutto no i wtedy pewnie lepiej jak to będzie `UserPreferences`

2023-11-04 12:21 UTC, michal-jablonski commented on Server/Entities/User.cs
> +    public Role Role { get; set; } = default!;
chyba ustalaliśmy że roli nie robimy, że wystarczy nam enum z podziałem na Client / Admin i dodać dziedziczenie z klasą `Client: User` wtedy User nie miałby zamówień tylko Client (preferencje Admin może mieć chyba)

2023-11-04 12:21 UTC, michal-jablonski commented on Server/Entities/ProductCategory.cs
> +    public ICollection<Product> Products { get; set; } = default!;
Potrzebujemy tych kategorii? Z wymagań mvc w teorii nie potrzebujemy, pytanie czy styknie 10 tabeli w bazie

2023-11-04 12:23 UTC, michal-jablonski commented
imo więcej sensu miałby ten podział niż tabela role w których i tak nie będziemy dodawać, a jak będzie podział user/client to można będzie jeszcze jakąs strategię zaimplementować

2023-11-04 19:09 UTC, MateuszMieczkowski commented on Server/Entities/ProductCategory.cs
> +    public ICollection<Product> Products { get; set; } = default!;
Zaznaczyliśmy wymaganie "możliwość ukrywania produktów i kategorii (np. w celu ich opublikowania dopiero po
skompletowaniu wszystkich danych). Elementy ukryte nie są widoczne dla klienta". Więc na razie bym zostawił, to jest Nullable więc jak coś to nie będziemy tego używać



























































M

2023-11-04 19:44 UTC, MateuszMieczkowski commented on Server/Entities/UserPreference.cs
> +}
Zrobione

2023-11-04 19:44 UTC, MateuszMieczkowski commented on Server/Entities/User.cs
> +    public Role Role { get; set; } = default!;
Zrobione

2023-11-04 20:28 UTC, michal-jablonski approved these changes

2023-11-04 20:28 UTC, merged